### ISSUE TITLE
Some weird stuff with the window hiding and not remembering position on dual monitors.

### ISSUE THREAD

**Issue by sclient** [lemasato/POE-Keyword-Notifier#7]
Has to do with it catching keyboard input, and if you hit enter it will hide. Not sure whats causing the window position to change.

**Comment by lemasato** [comment]
> if you hit enter it will hide

This was most likely because the "Close/X" button was on focus and pressing Enter would trigger it.
Fixed with [0.3.2](https://github.com/lemasato/POE-Keyword-Notifier/releases/tag/0.3.2).

Not sure about the window's position changing.
Could you report back if it happens on [0.3.2](https://github.com/lemasato/POE-Keyword-Notifier/releases/tag/0.3.2)?

**Comment by sclient** [comment]
Sure thing. It seems to set itself back to the prior position. Ill see if it still happens on this version.
